name: files
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.2
  posix: ^6.0.1
  stdlibc:
    git: git@github.com:canonical/stdlibc.dart
  win32: ^5.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
